# Generated by Django 5.2.5 on 2026-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
