# Generated by Django 5.2.5 on 2026-02-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
    ]
